from fastapi import FastAPI, Depends
from fastapi.security import OAuth2PasswordRequestForm
from contextlib import asynccontextmanager
from uuid import uuid4
from datetime import datetime

from app.core.database import init_db
from app.api.load_interest import router as load_interest_router
from app.core.security import create_access_token
from app.schemas.auth_login import Loginrequest
from app.schemas.load import LoadCreate, LoadResponse


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Initialize the database when the application starts
    print("Initializing database...")
    init_db()
    yield
    # Perform any necessary cleanup here when the application shuts down
    print("Shutting down application...")

app = FastAPI(lifespan=lifespan)

app.include_router(load_interest_router,
                   prefix="/load_interest")


@app.get("/")
async def read_root():
    return {"message": "Welcome to the HEAVEN!"}


@app.post("/auth/login")
async def login(form_data: OAuth2PasswordRequestForm = Depends()):
    user_payload = {
        "user_id": str(uuid4()),
        "company_id": str(uuid4()),
        "roles": "empresa"
    }

    token = create_access_token(user_payload)

    return {
        "access_token": token,
        "token_type": "bearer"
    }

    # return {"message": "Login successful"}


@app.post("/loads/", response_model=LoadResponse)
async def create_load(load: LoadCreate):
    # Simulate load creation logic
    new_load = LoadResponse(
        id=uuid4(),  # In a real application, this would be generated by the database
        title=load.title,
        description=load.description,
        weight_kg=load.weight,
        volume_m3=load.volume_m3,
        company_id=uuid4(),
        created_at=datetime.now()
    )
    return new_load


# @app.post("/{load_id}/interest")
# async def create_interest(load_id:):
#     return {"message": f"Interest created for load {load_id}"}


# @app.get("/health")
# async def health_check():
#     return {"status": "ok"}


# @app.get("/version")
# async def get_version():
#     return {"version": "1.0.0"}


# @app.get("/status")
# async def get_status():
#     return {"status": "running"}


# @app.get("/load_interest")
# async def load_interest_status():
#     return {"load_interest": "active"}
